const tableBody = document.querySelector("tbody");
const headers = document.querySelectorAll("thead th");
const brandFilter = document.querySelector("#brandFilter");
const PCIFilter = document.querySelector("#PCIFilter");
const GOFilter = document.querySelector("#GOFilter");
const searchBar = document.querySelector("#searchBar");
const productImage = document.querySelector(".col-span-3 img");
const productTitle = document.querySelector(".col-span-3 h2");
const productDescription = document.querySelector(".col-span-3 p");
const productCount = document.querySelector("#productCount");

const errorMessage = document.createElement("p");
errorMessage.textContent = "Aucun produit ne correspond aux filtres sélectionnés.";
errorMessage.style.color = "red";
errorMessage.style.textAlign = "center";
errorMessage.style.marginTop = "20px";

const productData = [
    {
        name: "Disque dur SSD Corsair Force MP600 CORE MINI 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 CORE MINI 2 To.jpg",
        description: "SSD Corsair Force MP600 CORE MINI 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 4950 Mo/s, écriture jusqu'à 4000 Mo/s",
        price: 199,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 CORE XT 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 CORE XT 1 To.jpg",
        description: "SSD Corsair Force MP600 CORE XT 1 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 4950 Mo/s, écriture jusqu'à 3900 Mo/s",
        price: 129,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 CORE XT 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 CORE XT 2 To.jpg",
        description: "SSD Corsair Force MP600 CORE XT 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 4950 Mo/s, écriture jusqu'à 4000 Mo/s",
        price: 249,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 CORE XT 4 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 CORE XT 4 To.jpg",
        description: "SSD Corsair Force MP600 CORE XT 4 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 4950 Mo/s, écriture jusqu'à 4000 Mo/s",
        price: 499,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 GS 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 GS 1 To.jpg",
        description: "SSD Corsair Force MP600 GS 1 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 5000 Mo/s, écriture jusqu'à 4400 Mo/s",
        price: 139,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 GS 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 GS 2 To.jpg",
        description: "SSD Corsair Force MP600 GS 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 5000 Mo/s, écriture jusqu'à 4400 Mo/s",
        price: 269,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 GS 500 Go",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 GS 500 Go.jpg",
        description: "SSD Corsair Force MP600 GS 500 Go, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 5000 Mo/s, écriture jusqu'à 4400 Mo/s",
        price: 99,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "500",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 MICRO 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 MICRO 1 To.jpg",
        description: "SSD Corsair Force MP600 MICRO 1 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 4950 Mo/s, écriture jusqu'à 4000 Mo/s",
        price: 149,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 MICRO 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 MICRO 2 To.jpg",
        description: "SSD Corsair Force MP600 MICRO 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 4950 Mo/s, écriture jusqu'à 4000 Mo/s",
        price: 279,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 MINI 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 MINI 2 To.jpg",
        description: "SSD Corsair Force MP600 MINI 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 4950 Mo/s, écriture jusqu'à 4000 Mo/s",
        price: 259,
        rating: 4,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO LPX 1 To (Blanc)",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO LPX 1 To (Blanc).jpg",
        description: "SSD Corsair Force MP600 PRO LPX 1 To (Blanc), interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 5800 Mo/s",
        price: 179,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO LPX 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO LPX 1 To.jpg",
        description: "SSD Corsair Force MP600 PRO LPX 1 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 5800 Mo/s",
        price: 179,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO LPX 2 To (Blanc)",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO LPX 2 To (Blanc).jpg",
        description: "SSD Corsair Force MP600 PRO LPX 2 To (Blanc), interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 6800 Mo/s",
        price: 349,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO LPX 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO LPX 2 To.jpg",
        description: "SSD Corsair Force MP600 PRO LPX 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 6800 Mo/s",
        price: 349,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO LPX 4 To (Blanc)",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO LPX 4 To (Blanc).jpg",
        description: "SSD Corsair Force MP600 PRO LPX 4 To (Blanc), interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 6800 Mo/s",
        price: 699,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO LPX 4 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO LPX 4 To.jpg",
        description: "SSD Corsair Force MP600 PRO LPX 4 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 6800 Mo/s",
        price: 699,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO LPX 8 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO LPX 8 To.jpg",
        description: "SSD Corsair Force MP600 PRO LPX 8 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 6800 Mo/s",
        price: 1299,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "8000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO XT 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO XT 1 To.jpg",
        description: "SSD Corsair Force MP600 PRO XT 1 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 5800 Mo/s",
        price: 189,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO XT 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO XT 2 To.jpg",
        description: "SSD Corsair Force MP600 PRO XT 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 6800 Mo/s",
        price: 369,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO XT 4 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO XT 4 To.jpg",
        description: "SSD Corsair Force MP600 PRO XT 4 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 6800 Mo/s",
        price: 729,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair Force MP600 PRO XT 8 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair Force MP600 PRO XT 8 To.jpg",
        description: "SSD Corsair Force MP600 PRO XT 8 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7100 Mo/s, écriture jusqu'à 6800 Mo/s",
        price: 1399,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "8000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 1 To Avec dissipateur (Blanc)",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 1 To Avec dissipateur (Blanc).jpg",
        description: "SSD Corsair MP600 ELITE 1 To Avec dissipateur (Blanc), interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 199,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 1 To Avec dissipateur",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 1 To Avec dissipateur.jpg",
        description: "SSD Corsair MP600 ELITE 1 To Avec dissipateur, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 199,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 1 To.jpg",
        description: "SSD Corsair MP600 ELITE 1 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 189,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 2 To Avec dissipateur (Blanc)",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 2 To Avec dissipateur (Blanc).jpg",
        description: "SSD Corsair MP600 ELITE 2 To Avec dissipateur (Blanc), interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 399,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 2 To Avec dissipateur",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 2 To Avec dissipateur.jpg",
        description: "SSD Corsair MP600 ELITE 2 To Avec dissipateur, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 399,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 2 To.jpg",
        description: "SSD Corsair MP600 ELITE 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 389,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 4 To Avec dissipateur (Blanc)",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 4 To Avec dissipateur (Blanc).jpg",
        description: "SSD Corsair MP600 ELITE 4 To Avec dissipateur (Blanc), interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 799,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 4 To Avec dissipateur",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 4 To Avec dissipateur.jpg",
        description: "SSD Corsair MP600 ELITE 4 To Avec dissipateur, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 799,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 ELITE 4 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 ELITE 4 To.jpg",
        description: "SSD Corsair MP600 ELITE 4 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 789,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 Pro NH 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 Pro NH 1 To.jpg",
        description: "SSD Corsair MP600 Pro NH 1 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 199,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 Pro NH 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 Pro NH 2 To.jpg",
        description: "SSD Corsair MP600 Pro NH 2 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 399,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 Pro NH 4 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 Pro NH 4 To.jpg",
        description: "SSD Corsair MP600 Pro NH 4 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 799,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP600 Pro NH 8 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP600 Pro NH 8 To.jpg",
        description: "SSD Corsair MP600 Pro NH 8 To, interface PCIe Gen4 x4, format M.2 2280, lecture jusqu'à 7000 Mo/s, écriture jusqu'à 6000 Mo/s",
        price: 1499,
        rating: 5,
        brand: "Corsair",
        PCI: "4.4",
        GO: "8000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 ELITE 1 To - Avec dissipateur",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 ELITE 1 To - Avec dissipateur.jpg",
        description: "SSD Corsair MP700 ELITE 1 To - Avec dissipateur, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 10000 Mo/s, écriture jusqu'à 9500 Mo/s",
        price: 299,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 ELITE 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 ELITE 1 To.jpg",
        description: "SSD Corsair MP700 ELITE 1 To, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 10000 Mo/s, écriture jusqu'à 9500 Mo/s",
        price: 289,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 ELITE 2 To - Avec dissipateur",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 ELITE 2 To - Avec dissipateur.jpg",
        description: "SSD Corsair MP700 ELITE 2 To - Avec dissipateur, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 10000 Mo/s, écriture jusqu'à 9500 Mo/s",
        price: 599,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 ELITE 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 ELITE 2 To.jpg",
        description: "SSD Corsair MP700 ELITE 2 To, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 10000 Mo/s, écriture jusqu'à 9500 Mo/s",
        price: 589,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO 1 To avec dissipateur actif",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO 1 To avec dissipateur actif.jpg",
        description: "SSD Corsair MP700 PRO 1 To avec dissipateur actif, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 349,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO 1 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO 1 To.jpg",
        description: "SSD Corsair MP700 PRO 1 To, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 339,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "1000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO 2 To avec dissipateur actif",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO 2 To avec dissipateur actif.jpg",
        description: "SSD Corsair MP700 PRO 2 To avec dissipateur actif, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 699,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO 2 To.jpg",
        description: "SSD Corsair MP700 PRO 2 To, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 689,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO 4 To avec dissipateur actif",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO 4 To avec dissipateur actif.jpg",
        description: "SSD Corsair MP700 PRO 4 To avec dissipateur actif, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 1399,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO SE 2 To avec dissipateur actif",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO SE 2 To avec dissipateur actif.jpg",
        description: "SSD Corsair MP700 PRO SE 2 To avec dissipateur actif, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 749,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO SE 4 To avec dissipateur actif",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO SE 4 To avec dissipateur actif.jpg",
        description: "SSD Corsair MP700 PRO SE 4 To avec dissipateur actif, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 1499,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO SE 4 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO SE 4 To.jpg",
        description: "SSD Corsair MP700 PRO SE 4 To, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 1499,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "4000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO SE Hydro X Series 2 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO SE Hydro X Series 2 To.jpg",
        description: "SSD Corsair MP700 PRO SE Hydro X Series 2 To, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 799,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "2000",
        availability: "green",
        },
        {
        name: "Disque dur SSD Corsair MP700 PRO SE Hydro X Series 4 To",
        image: "/Website Beta/IMAGES/images composants/SSD/Corsair/Corsair MP700 PRO SE Hydro X Series 4 To.jpg",
        description: "SSD Corsair MP700 PRO SE Hydro X Series 4 To, interface PCIe Gen5 x4, format M.2 2280, lecture jusqu'à 12000 Mo/s, écriture jusqu'à 10000 Mo/s",
        price: 1599,
        rating: 5,
        brand: "Corsair",
        PCI: "5.4",
        GO: "4000",
        availability: "green",
        },
        {
            name: "Disque dur SSD Crucial BX500 1 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial BX500 1 To.jpg",
            description: "SSD interne 2.5\" SATA III 1 To - Lecture 540 Mo/s, Ecriture 500 Mo/s - Crucial BX500",
            price: 89.99,
            rating: 4,
            brand: "Crucial",
            PCI: "ATA",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial BX500 2 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial BX500 2 To.jpg",
            description: "SSD interne 2.5\" SATA III 2 To - Lecture 540 Mo/s, Ecriture 500 Mo/s - Crucial BX500",
            price: 179.99,
            rating: 4,
            brand: "Crucial",
            PCI: "ATA",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial BX500 240 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial BX500 240 Go.jpg",
            description: "SSD interne 2.5\" SATA III 240 Go - Lecture 540 Mo/s, Ecriture 500 Mo/s - Crucial BX500",
            price: 39.99,
            rating: 4,
            brand: "Crucial",
            PCI: "ATA",
            GO: "240",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial BX500 500 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial BX500 500 Go.jpg",
            description: "SSD interne 2.5\" SATA III 500 Go - Lecture 540 Mo/s, Ecriture 500 Mo/s - Crucial BX500",
            price: 59.99,
            rating: 4,
            brand: "Crucial",
            PCI: "ATA",
            GO: "500",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P3 1 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P3 1 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P3",
            price: 109.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P3 2 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P3 2 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P3",
            price: 199.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P3 4 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P3 4 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P3",
            price: 399.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P3 500 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P3 500 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 500 Go - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P3",
            price: 79.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "500",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P3 Plus 1 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P3 Plus 1 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 5000 Mo/s, Ecriture 4200 Mo/s - Crucial P3 Plus",
            price: 119.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P3 Plus 2 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P3 Plus 2 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 5000 Mo/s, Ecriture 4200 Mo/s - Crucial P3 Plus",
            price: 219.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P3 Plus 4 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P3 Plus 4 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 5000 Mo/s, Ecriture 4200 Mo/s - Crucial P3 Plus",
            price: 429.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P3 Plus 500 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P3 Plus 500 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 500 Go - Lecture 5000 Mo/s, Ecriture 4200 Mo/s - Crucial P3 Plus",
            price: 89.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "500",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P310 1 To 2230",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P310 1 To 2230.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P310",
            price: 129.99,
            rating: 4,
            brand: "Crucial",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P310 1 To 2280 - Avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P310 1 To 2280 - Avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P310 avec dissipateur",
            price: 139.99,
            rating: 4,
            brand: "Crucial",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P310 1 To 2280",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P310 1 To 2280.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P310",
            price: 129.99,
            rating: 4,
            brand: "Crucial",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P310 2 To 2230",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P310 2 To 2230.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P310",
            price: 249.99,
            rating: 4,
            brand: "Crucial",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P310 2 To 2280 - Avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P310 2 To 2280 - Avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P310 avec dissipateur",
            price: 259.99,
            rating: 4,
            brand: "Crucial",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P310 2 To 2280",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P310 2 To 2280.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P310",
            price: 249.99,
            rating: 4,
            brand: "Crucial",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial P310 500 Go 2280",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial P310 500 Go 2280.jpg",
            description: "SSD interne M.2 PCIe NVMe 500 Go - Lecture 3500 Mo/s, Ecriture 3000 Mo/s - Crucial P310",
            price: 89.99,
            rating: 4,
            brand: "Crucial",
            PCI: "4.4",
            GO: "500",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T500 1 To avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T500 1 To avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 7400 Mo/s, Ecriture 7000 Mo/s - Crucial T500 avec dissipateur",
            price: 149.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T500 1 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T500 1 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 7400 Mo/s, Ecriture 7000 Mo/s - Crucial T500",
            price: 139.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T500 2 To avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T500 2 To avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 7400 Mo/s, Ecriture 7000 Mo/s - Crucial T500 avec dissipateur",
            price: 279.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T500 2 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T500 2 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 7400 Mo/s, Ecriture 7000 Mo/s - Crucial T500",
            price: 269.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T500 4 To avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T500 4 To avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 7400 Mo/s, Ecriture 7000 Mo/s - Crucial T500 avec dissipateur",
            price: 549.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T500 4 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T500 4 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 7400 Mo/s, Ecriture 7000 Mo/s - Crucial T500",
            price: 539.99,
            rating: 5,
            brand: "Crucial",
            PCI: "4.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T700 1 To avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T700 1 To avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T700 avec dissipateur",
            price: 199.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T700 1 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T700 1 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T700",
            price: 189.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T700 2 To avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T700 2 To avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T700 avec dissipateur",
            price: 399.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T700 2 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T700 2 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T700",
            price: 389.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T700 4 To avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T700 4 To avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T700 avec dissipateur",
            price: 799.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T700 4 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T700 4 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T700",
            price: 789.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T705 1 To - Avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T705 1 To - Avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T705 avec dissipateur",
            price: 209.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T705 1 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T705 1 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T705",
            price: 199.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T705 2 To - Avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T705 2 To - Avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T705 avec dissipateur",
            price: 419.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T705 2 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T705 2 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T705",
            price: 409.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T705 4 To - Avec dissipateur",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T705 4 To - Avec dissipateur.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T705 avec dissipateur",
            price: 829.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Crucial T705 4 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Crucial/Crucial T705 4 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 12400 Mo/s, Ecriture 11800 Mo/s - Crucial T705",
            price: 819.99,
            rating: 5,
            brand: "Crucial",
            PCI: "5.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston DC600M 1.92 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston DC600M 1.92 To.jpg",
            description: "SSD interne 2.5\" SATA III 1.92 To - Lecture 550 Mo/s, Ecriture 520 Mo/s - Kingston DC600M",
            price: 499.99,
            rating: 4,
            brand: "Kingston",
            PCI: "ATA",
            GO: "1920",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston DC600M 3.84 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston DC600M 3.84 To.jpg",
            description: "SSD interne 2.5\" SATA III 3.84 To - Lecture 550 Mo/s, Ecriture 520 Mo/s - Kingston DC600M",
            price: 999.99,
            rating: 4,
            brand: "Kingston",
            PCI: "ATA",
            GO: "3840",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston DC600M 7.68 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston DC600M 7.68 To.jpg",
            description: "SSD interne 2.5\" SATA III 7.68 To - Lecture 550 Mo/s, Ecriture 520 Mo/s - Kingston DC600M",
            price: 1999.99,
            rating: 4,
            brand: "Kingston",
            PCI: "ATA",
            GO: "7680",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston FURY Renegade 1 To avec dissipateur thermique",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston FURY Renegade 1 To avec dissipateur thermique.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 7300 Mo/s, Ecriture 6000 Mo/s - Kingston FURY Renegade avec dissipateur",
            price: 149.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston FURY Renegade 1 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston FURY Renegade 1 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 7300 Mo/s, Ecriture 6000 Mo/s - Kingston FURY Renegade",
            price: 139.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston FURY Renegade 2 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston FURY Renegade 2 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 7300 Mo/s, Ecriture 7000 Mo/s - Kingston FURY Renegade",
            price: 279.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston FURY Renegade 4 To avec dissipateur thermique",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston FURY Renegade 4 To avec dissipateur thermique.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 7300 Mo/s, Ecriture 7000 Mo/s - Kingston FURY Renegade avec dissipateur",
            price: 549.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston FURY Renegade 4 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston FURY Renegade 4 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 7300 Mo/s, Ecriture 7000 Mo/s - Kingston FURY Renegade",
            price: 539.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston FURY Renegade 500 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston FURY Renegade 500 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 500 Go - Lecture 7300 Mo/s, Ecriture 3900 Mo/s - Kingston FURY Renegade",
            price: 89.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "500",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston KC3000 1024 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston KC3000 1024 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 7000 Mo/s, Ecriture 6000 Mo/s - Kingston KC3000",
            price: 129.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston KC3000 2048 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston KC3000 2048 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 7000 Mo/s, Ecriture 7000 Mo/s - Kingston KC3000",
            price: 249.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston KC3000 4096 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston KC3000 4096 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 7000 Mo/s, Ecriture 7000 Mo/s - Kingston KC3000",
            price: 499.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston KC3000 512 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston KC3000 512 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 512 Go - Lecture 7000 Mo/s, Ecriture 3900 Mo/s - Kingston KC3000",
            price: 89.99,
            rating: 5,
            brand: "Kingston",
            PCI: "4.4",
            GO: "512",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston KC600 1 To mSATA",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston KC600 1 To mSATA.jpg",
            description: "SSD interne mSATA 1 To - Lecture 550 Mo/s, Ecriture 520 Mo/s - Kingston KC600",
            price: 149.99,
            rating: 4,
            brand: "Kingston",
            PCI: "mSATA",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston KC600 256 Go mSATA",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston KC600 256 Go mSATA.jpg",
            description: "SSD interne mSATA 256 Go - Lecture 550 Mo/s, Ecriture 520 Mo/s - Kingston KC600",
            price: 59.99,
            rating: 4,
            brand: "Kingston",
            PCI: "mSATA",
            GO: "256",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston KC600 512 Go mSATA",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston KC600 512 Go mSATA.jpg",
            description: "SSD interne mSATA 512 Go - Lecture 550 Mo/s, Ecriture 520 Mo/s - Kingston KC600",
            price: 99.99,
            rating: 4,
            brand: "Kingston",
            PCI: "mSATA",
            GO: "512",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston KC600 512 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston KC600 512 Go.jpg",
            description: "SSD interne 2.5\" SATA III 512 Go - Lecture 550 Mo/s, Ecriture 520 Mo/s - Kingston KC600",
            price: 79.99,
            rating: 4,
            brand: "Kingston",
            PCI: "ATA",
            GO: "512",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston SSD A400 240 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston SSD A400 240 Go.jpg",
            description: "SSD interne 2.5\" SATA III 240 Go - Lecture 500 Mo/s, Ecriture 350 Mo/s - Kingston A400",
            price: 39.99,
            rating: 4,
            brand: "Kingston",
            PCI: "ATA",
            GO: "240",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston SSD A400 480 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston SSD A400 480 Go.jpg",
            description: "SSD interne 2.5\" SATA III 480 Go - Lecture 500 Mo/s, Ecriture 450 Mo/s - Kingston A400",
            price: 59.99,
            rating: 4,
            brand: "Kingston",
            PCI: "ATA",
            GO: "480",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston SSD A400 960 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston SSD A400 960 Go.jpg",
            description: "SSD interne 2.5\" SATA III 960 Go - Lecture 500 Mo/s, Ecriture 450 Mo/s - Kingston A400",
            price: 99.99,
            rating: 4,
            brand: "Kingston",
            PCI: "ATA",
            GO: "960",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston SSD NV2 500 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston SSD NV2 500 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 500 Go - Lecture 3500 Mo/s, Ecriture 2100 Mo/s - Kingston NV2",
            price: 59.99,
            rating: 4,
            brand: "Kingston",
            PCI: "4.4",
            GO: "500",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston SSD NV3 1 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston SSD NV3 1 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 1 To - Lecture 3500 Mo/s, Ecriture 2100 Mo/s - Kingston NV3",
            price: 109.99,
            rating: 4,
            brand: "Kingston",
            PCI: "4.4",
            GO: "1000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston SSD NV3 2 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston SSD NV3 2 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 2 To - Lecture 3500 Mo/s, Ecriture 2800 Mo/s - Kingston NV3",
            price: 199.99,
            rating: 4,
            brand: "Kingston",
            PCI: "4.4",
            GO: "2000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston SSD NV3 4 To",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston SSD NV3 4 To.jpg",
            description: "SSD interne M.2 PCIe NVMe 4 To - Lecture 3500 Mo/s, Ecriture 2800 Mo/s - Kingston NV3",
            price: 399.99,
            rating: 4,
            brand: "Kingston",
            PCI: "4.4",
            GO: "4000",
            availability: "green",
        },
        {
            name: "Disque dur SSD Kingston SSD NV3 500 Go",
            image: "/Website Beta/IMAGES/images composants/SSD/Kingston/Kingston SSD NV3 500 Go.jpg",
            description: "SSD interne M.2 PCIe NVMe 500 Go - Lecture 3500 Mo/s, Ecriture 2100 Mo/s - Kingston NV3",
            price: 69.99,
            rating: 4,
            brand: "Kingston",
            PCI: "4.4",
            GO: "500",
            availability: "green",
        },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 1 To.jpg",
                description: "SSD Samsung 870 EVO 1 To - SATA III - 2.5\" - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 89,
                rating: 5,
                brand: "Samsung",
                PCI: "ATA",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 2 To.jpg",
                description: "SSD Samsung 870 EVO 2 To - SATA III - 2.5\" - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 179,
                rating: 5,
                brand: "Samsung",
                PCI: "ATA",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 250 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 250 Go.jpg",
                description: "SSD Samsung 870 EVO 250 Go - SATA III - 2.5\" - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 49,
                rating: 4,
                brand: "Samsung",
                PCI: "ATA",
                GO: "250",
                availability: "orange",
            },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 4 To.jpg",
                description: "SSD Samsung 870 EVO 4 To - SATA III - 2.5\" - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 399,
                rating: 5,
                brand: "Samsung",
                PCI: "ATA",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 500 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 500 Go.jpg",
                description: "SSD Samsung 870 EVO 500 Go - SATA III - 2.5\" - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 69,
                rating: 4,
                brand: "Samsung",
                PCI: "ATA",
                GO: "500",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 980 M.2 PCIe NVMe 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 980 M.2 PCIe NVMe 1 To.jpg",
                description: "SSD Samsung 980 1 To - M.2 PCIe NVMe - Lecture : 3500 Mo/s - Écriture : 3000 Mo/s",
                price: 109,
                rating: 5,
                brand: "Samsung",
                PCI: "3.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 980 M.2 PCIe NVMe 250 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 980 M.2 PCIe NVMe 250 Go.jpg",
                description: "SSD Samsung 980 250 Go - M.2 PCIe NVMe - Lecture : 2900 Mo/s - Écriture : 1300 Mo/s",
                price: 49,
                rating: 4,
                brand: "Samsung",
                PCI: "3.4",
                GO: "250",
                availability: "orange",
            },
            {
                name: "Disque dur SSD Samsung SSD 980 M.2 PCIe NVMe 500 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 980 M.2 PCIe NVMe 500 Go.jpg",
                description: "SSD Samsung 980 500 Go - M.2 PCIe NVMe - Lecture : 3500 Mo/s - Écriture : 3000 Mo/s",
                price: 79,
                rating: 5,
                brand: "Samsung",
                PCI: "3.4",
                GO: "500",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 EVO Plus M.2 PCIe NVMe 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 EVO Plus M.2 PCIe NVMe 1 To.jpg",
                description: "SSD Samsung 990 EVO Plus 1 To - M.2 PCIe NVMe - Lecture : 3500 Mo/s - Écriture : 3300 Mo/s",
                price: 129,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 EVO Plus M.2 PCIe NVMe 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 EVO Plus M.2 PCIe NVMe 2 To.jpg",
                description: "SSD Samsung 990 EVO Plus 2 To - M.2 PCIe NVMe - Lecture : 3500 Mo/s - Écriture : 3300 Mo/s",
                price: 249,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 EVO Plus M.2 PCIe NVMe 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 EVO Plus M.2 PCIe NVMe 4 To.jpg",
                description: "SSD Samsung 990 EVO Plus 4 To - M.2 PCIe NVMe - Lecture : 3500 Mo/s - Écriture : 3300 Mo/s",
                price: 499,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 1 To avec dissipateur",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 1 To avec dissipateur.jpg",
                description: "SSD Samsung 990 PRO 1 To - M.2 PCIe NVMe - Lecture : 7450 Mo/s - Écriture : 6900 Mo/s - Avec dissipateur",
                price: 149,
                rating: 5,
                brand: "Samsung",
                PCI: "5.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 1 To.jpg",
                description: "SSD Samsung 990 PRO 1 To - M.2 PCIe NVMe - Lecture : 7450 Mo/s - Écriture : 6900 Mo/s",
                price: 139,
                rating: 5,
                brand: "Samsung",
                PCI: "5.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 2 To avec dissipateur",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 2 To avec dissipateur.jpg",
                description: "SSD Samsung 990 PRO 2 To - M.2 PCIe NVMe - Lecture : 7450 Mo/s - Écriture : 6900 Mo/s - Avec dissipateur",
                price: 279,
                rating: 5,
                brand: "Samsung",
                PCI: "5.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 2 To.jpg",
                description: "SSD Samsung 990 PRO 2 To - M.2 PCIe NVMe - Lecture : 7450 Mo/s - Écriture : 6900 Mo/s",
                price: 269,
                rating: 5,
                brand: "Samsung",
                PCI: "5.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 4 To avec dissipateur",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 4 To avec dissipateur.jpg",
                description: "SSD Samsung 990 PRO 4 To - M.2 PCIe NVMe - Lecture : 7450 Mo/s - Écriture : 6900 Mo/s - Avec dissipateur",
                price: 549,
                rating: 5,
                brand: "Samsung",
                PCI: "5.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 4 To.jpg",
                description: "SSD Samsung 990 PRO 4 To - M.2 PCIe NVMe - Lecture : 7450 Mo/s - Écriture : 6900 Mo/s",
                price: 529,
                rating: 5,
                brand: "Samsung",
                PCI: "5.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 1 To - Avec dissipateur thermique",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 1 To - Avec dissipateur thermique.jpg",
                description: "SSD WD Black SN850X 1 To - M.2 PCIe NVMe - Lecture : 7300 Mo/s - Écriture : 6300 Mo/s - Avec dissipateur",
                price: 129,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 1 To.jpg",
                description: "SSD WD Black SN850X 1 To - M.2 PCIe NVMe - Lecture : 7300 Mo/s - Écriture : 6300 Mo/s",
                price: 119,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 2 To - Avec dissipateur thermique",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 2 To - Avec dissipateur thermique.jpg",
                description: "SSD WD Black SN850X 2 To - M.2 PCIe NVMe - Lecture : 7300 Mo/s - Écriture : 6300 Mo/s - Avec dissipateur",
                price: 249,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 2 To -",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 2 To -.jpg",
                description: "SSD WD Black SN850X 2 To - M.2 PCIe NVMe - Lecture : 7300 Mo/s - Écriture : 6300 Mo/s",
                price: 239,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 4 To.jpg",
                description: "SSD WD Black SN850X 4 To - M.2 PCIe NVMe - Lecture : 7300 Mo/s - Écriture : 6300 Mo/s",
                price: 499,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD_Black SN770 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD_Black SN770 1 To.jpg",
                description: "SSD WD Black SN770 1 To - M.2 PCIe NVMe - Lecture : 5150 Mo/s - Écriture : 4900 Mo/s",
                price: 99,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD_Black SN770 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD_Black SN770 2 To.jpg",
                description: "SSD WD Black SN770 2 To - M.2 PCIe NVMe - Lecture : 5150 Mo/s - Écriture : 4900 Mo/s",
                price: 199,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD_Black SN770 250 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD_Black SN770 250 Go.jpg",
                description: "SSD WD Black SN770 250 Go - M.2 PCIe NVMe - Lecture : 4000 Mo/s - Écriture : 2000 Mo/s",
                price: 49,
                rating: 4,
                brand: "WDB",
                PCI: "4.4",
                GO: "250",
                availability: "orange",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD_Black SN770 500 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD_Black SN770 500 Go.jpg",
                description: "SSD WD Black SN770 500 Go - M.2 PCIe NVMe - Lecture : 5150 Mo/s - Écriture : 4900 Mo/s",
                price: 79,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "500",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD M.2 WD Red SN700 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD M.2 WD Red SN700 2 To.jpg",
                description: "SSD WD Red SN700 2 To - M.2 PCIe NVMe - Lecture : 3400 Mo/s - Écriture : 3100 Mo/s",
                price: 199,
                rating: 5,
                brand: "WDB",
                PCI: "3.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD M.2 WD Red SN700 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD M.2 WD Red SN700 4 To.jpg",
                description: "SSD WD Red SN700 4 To - M.2 PCIe NVMe - Lecture : 3400 Mo/s - Écriture : 3100 Mo/s",
                price: 399,
                rating: 5,
                brand: "WDB",
                PCI: "3.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Western Digital SSD M.2 WD Red SN700 500 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD M.2 WD Red SN700 500 Go.jpg",
                description: "SSD WD Red SN700 500 Go - M.2 PCIe NVMe - Lecture : 3400 Mo/s - Écriture : 3100 Mo/s",
                price: 89,
                rating: 5,
                brand: "WDB",
                PCI: "3.4",
                GO: "500",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 1 To - 2.5",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 1 To - 2.5.jpg",
                description: "SSD WD Blue SA510 1 To - SATA III - 2.5\" - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 89,
                rating: 5,
                brand: "WDB",
                PCI: "ATA",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 1 To - M.2",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 1 To - M.2.jpg",
                description: "SSD WD Blue SA510 1 To - M.2 SATA - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 89,
                rating: 5,
                brand: "WDB",
                PCI: "SATA",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 2 To - 2.5",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 2 To - 2.5.jpg",
                description: "SSD WD Blue SA510 2 To - SATA III - 2.5\" - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 179,
                rating: 5,
                brand: "WDB",
                PCI: "ATA",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 2 To - M.2",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 2 To - M.2.jpg",
                description: "SSD WD Blue SA510 2 To - M.2 SATA - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 179,
                rating: 5,
                brand: "WDB",
                PCI: "SATA",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 250 Go - M.2",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 250 Go - M.2.jpg",
                description: "SSD WD Blue SA510 250 Go - M.2 SATA - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 49,
                rating: 4,
                brand: "WDB",
                PCI: "SATA",
                GO: "250",
                availability: "orange",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 500 Go - 2.5",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 500 Go - 2.5.jpg",
                description: "SSD WD Blue SA510 500 Go - SATA III - 2.5\" - Lecture : 560 Mo/s - Écriture : 530 Mo/s",
                price: 69,
                rating: 5,
                brand: "WDB",
                PCI: "ATA",
                GO: "500",
                availability: "green",
            },
        
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 1 To.jpg",
                description: "SSD Samsung 870 EVO 1 To - SATA III - 2.5\"",
                price: 89,
                rating: 5,
                brand: "Samsung",
                PCI: "ATA",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 2 To.jpg",
                description: "SSD Samsung 870 EVO 2 To - SATA III - 2.5\"",
                price: 159,
                rating: 5,
                brand: "Samsung",
                PCI: "ATA",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 250 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 250 Go.jpg",
                description: "SSD Samsung 870 EVO 250 Go - SATA III - 2.5\"",
                price: 49,
                rating: 4,
                brand: "Samsung",
                PCI: "ATA",
                GO: "250",
                availability: "orange",
            },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 4 To.jpg",
                description: "SSD Samsung 870 EVO 4 To - SATA III - 2.5\"",
                price: 349,
                rating: 5,
                brand: "Samsung",
                PCI: "ATA",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Samsung SSD 870 EVO 500 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 870 EVO 500 Go.jpg",
                description: "SSD Samsung 870 EVO 500 Go - SATA III - 2.5\"",
                price: 69,
                rating: 5,
                brand: "Samsung",
                PCI: "ATA",
                GO: "500",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 980 M.2 PCIe NVMe 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 980 M.2 PCIe NVMe 1 To.jpg",
                description: "SSD Samsung 980 1 To - M.2 PCIe NVMe 3.0 x4",
                price: 99,
                rating: 5,
                brand: "Samsung",
                PCI: "3.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 980 M.2 PCIe NVMe 250 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 980 M.2 PCIe NVMe 250 Go.jpg",
                description: "SSD Samsung 980 250 Go - M.2 PCIe NVMe 3.0 x4",
                price: 49,
                rating: 4,
                brand: "Samsung",
                PCI: "3.4",
                GO: "250",
                availability: "orange",
            },
            {
                name: "Disque dur SSD Samsung SSD 980 M.2 PCIe NVMe 500 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 980 M.2 PCIe NVMe 500 Go.jpg",
                description: "SSD Samsung 980 500 Go - M.2 PCIe NVMe 3.0 x4",
                price: 69,
                rating: 5,
                brand: "Samsung",
                PCI: "3.4",
                GO: "500",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 EVO Plus M.2 PCIe NVMe 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 EVO Plus M.2 PCIe NVMe 1 To.jpg",
                description: "SSD Samsung 990 EVO Plus 1 To - M.2 PCIe NVMe 4.0 x4",
                price: 129,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 EVO Plus M.2 PCIe NVMe 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 EVO Plus M.2 PCIe NVMe 2 To.jpg",
                description: "SSD Samsung 990 EVO Plus 2 To - M.2 PCIe NVMe 4.0 x4",
                price: 229,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 EVO Plus M.2 PCIe NVMe 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 EVO Plus M.2 PCIe NVMe 4 To.jpg",
                description: "SSD Samsung 990 EVO Plus 4 To - M.2 PCIe NVMe 4.0 x4",
                price: 449,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 1 To avec dissipateur",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 1 To avec dissipateur.jpg",
                description: "SSD Samsung 990 PRO 1 To - M.2 PCIe NVMe 4.0 x4 avec dissipateur",
                price: 149,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 1 To.jpg",
                description: "SSD Samsung 990 PRO 1 To - M.2 PCIe NVMe 4.0 x4",
                price: 139,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 2 To avec dissipateur",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 2 To avec dissipateur.jpg",
                description: "SSD Samsung 990 PRO 2 To - M.2 PCIe NVMe 4.0 x4 avec dissipateur",
                price: 259,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 2 To.jpg",
                description: "SSD Samsung 990 PRO 2 To - M.2 PCIe NVMe 4.0 x4",
                price: 249,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 4 To avec dissipateur",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 4 To avec dissipateur.jpg",
                description: "SSD Samsung 990 PRO 4 To - M.2 PCIe NVMe 4.0 x4 avec dissipateur",
                price: 499,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Samsung SSD 990 PRO M.2 PCIe NVMe 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Samsung/Samsung SSD 990 PRO M.2 PCIe NVMe 4 To.jpg",
                description: "SSD Samsung 990 PRO 4 To - M.2 PCIe NVMe 4.0 x4",
                price: 489,
                rating: 5,
                brand: "Samsung",
                PCI: "4.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 1 To - Avec dissipateur thermique",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 1 To - Avec dissipateur thermique.jpg",
                description: "SSD WD Black SN850X 1 To - M.2 PCIe NVMe 4.0 x4 avec dissipateur",
                price: 129,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 1 To.jpg",
                description: "SSD WD Black SN850X 1 To - M.2 PCIe NVMe 4.0 x4",
                price: 119,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 2 To - Avec dissipateur thermique",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 2 To - Avec dissipateur thermique.jpg",
                description: "SSD WD Black SN850X 2 To - M.2 PCIe NVMe 4.0 x4 avec dissipateur",
                price: 229,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 2 To -",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 2 To -.jpg",
                description: "SSD WD Black SN850X 2 To - M.2 PCIe NVMe 4.0 x4",
                price: 219,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Black SN850X 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD Black SN850X 4 To.jpg",
                description: "SSD WD Black SN850X 4 To - M.2 PCIe NVMe 4.0 x4",
                price: 449,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD_Black SN770 1 To",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD_Black SN770 1 To.jpg",
                description: "SSD WD Black SN770 1 To - M.2 PCIe NVMe 4.0 x4",
                price: 99,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD_Black SN770 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD_Black SN770 2 To.jpg",
                description: "SSD WD Black SN770 2 To - M.2 PCIe NVMe 4.0 x4",
                price: 179,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD_Black SN770 250 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD_Black SN770 250 Go.jpg",
                description: "SSD WD Black SN770 250 Go - M.2 PCIe NVMe 4.0 x4",
                price: 49,
                rating: 4,
                brand: "WDB",
                PCI: "4.4",
                GO: "250",
                availability: "orange",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD_Black SN770 500 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/WD_Black/Western Digital SSD WD_Black SN770 500 Go.jpg",
                description: "SSD WD Black SN770 500 Go - M.2 PCIe NVMe 4.0 x4",
                price: 69,
                rating: 5,
                brand: "WDB",
                PCI: "4.4",
                GO: "500",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD M.2 WD Red SN700 2 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD M.2 WD Red SN700 2 To.jpg",
                description: "SSD WD Red SN700 2 To - M.2 PCIe NVMe 3.0 x4",
                price: 199,
                rating: 5,
                brand: "WDB",
                PCI: "3.4",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD M.2 WD Red SN700 4 To",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD M.2 WD Red SN700 4 To.jpg",
                description: "SSD WD Red SN700 4 To - M.2 PCIe NVMe 3.0 x4",
                price: 399,
                rating: 5,
                brand: "WDB",
                PCI: "3.4",
                GO: "4000",
                availability: "blue",
            },
            {
                name: "Disque dur SSD Western Digital SSD M.2 WD Red SN700 500 Go",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD M.2 WD Red SN700 500 Go.jpg",
                description: "SSD WD Red SN700 500 Go - M.2 PCIe NVMe 3.0 x4",
                price: 79,
                rating: 5,
                brand: "WDB",
                PCI: "3.4",
                GO: "500",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 1 To - 2.5",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 1 To - 2.5.jpg",
                description: "SSD WD Blue SA510 1 To - SATA III - 2.5\"",
                price: 89,
                rating: 5,
                brand: "WDB",
                PCI: "ATA",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 1 To - M.2",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 1 To - M.2.jpg",
                description: "SSD WD Blue SA510 1 To - SATA III - M.2",
                price: 89,
                rating: 5,
                brand: "WDB",
                PCI: "ATA",
                GO: "1000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 2 To - 2.5",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 2 To - 2.5.jpg",
                description: "SSD WD Blue SA510 2 To - SATA III - 2.5\"",
                price: 159,
                rating: 5,
                brand: "WDB",
                PCI: "ATA",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 2 To - M.2",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 2 To - M.2.jpg",
                description: "SSD WD Blue SA510 2 To - SATA III - M.2",
                price: 159,
                rating: 5,
                brand: "WDB",
                PCI: "ATA",
                GO: "2000",
                availability: "green",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 250 Go - M.2",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 250 Go - M.2.jpg",
                description: "SSD WD Blue SA510 250 Go - SATA III - M.2",
                price: 49,
                rating: 4,
                brand: "WDB",
                PCI: "ATA",
                GO: "250",
                availability: "orange",
            },
            {
                name: "Disque dur SSD Western Digital SSD WD Blue SA510 500 Go - 2.5",
                image: "/Website Beta/IMAGES/images composants/SSD/Western Digital/Western Digital SSD WD Blue SA510 500 Go - 2.5.jpg",
                description: "SSD WD Blue SA510 500 Go - SATA III - 2.5\"",
                price: 69,
                rating: 5,
                brand: "WDB",
                PCI: "ATA",
                GO: "500",
                availability: "green",
            }
];

let sortOrder = {
    rating: 1,
    price: 1,
    availability: 1
};

function applyFiltersAndSort() {
    let filteredData = productData.filter(product => {
        const matchesBrand = !brandFilter.value || product.brand === brandFilter.value;
        const matchesPCI = !PCIFilter.value || product.PCI === PCIFilter.value;
        const matchesGO = !GOFilter.value || product.GO === GOFilter.value;
        const matchesSearch = !searchBar.value || product.name.toLowerCase().includes(searchBar.value.toLowerCase());
        return matchesBrand && matchesPCI && matchesGO && matchesSearch;
    });

    const headerClicked = Array.from(headers).find(h => h.classList.contains("sorted"));
    if (headerClicked) {
        const index = Array.from(headers).indexOf(headerClicked);
        if (index === 2) {
            filteredData.sort((a, b) => sortOrder.rating * (a.rating - b.rating));
        } else if (index === 3) {
            filteredData.sort((a, b) => sortOrder.price * (a.price - b.price));
        } else if (index === 4) {
            filteredData.sort((a, b) => sortOrder.availability * (a.availability.localeCompare(b.availability)));
        }
    }

    renderTable(filteredData);
    updateProductCount(filteredData.length);

    if (filteredData.length === 0) {
        tableBody.innerHTML = "";
        tableBody.parentNode.appendChild(errorMessage);
        productImage.src = "/Website Beta/IMAGES/Image complémentaires/Interdiction.jpg";
        productTitle.textContent = "";
        productDescription.textContent = "";
    } else {
        if (errorMessage.parentNode) {
            errorMessage.parentNode.removeChild(errorMessage);
        }
    }
}

function renderTable(data) {
    tableBody.innerHTML = "";
    data.forEach(product => {
        const row = `
            <tr class="border-t">
                <td class="p-3">
                    <input type="checkbox" class="mr-2">${product.name}
                </td>
                <td class="p-3"></td>
                <td class="p-3">
                    <div class="star-rating" data-rating="${product.rating}">
                        ${renderStars(product.rating)}
                    </div>
                </td>
                <td class="p-3 price">${product.price.toFixed(2)}€</td>
                <td class="p-3">${getAvailabilityBadge(product.availability)}</td>
            </tr>
        `;
        tableBody.insertAdjacentHTML("beforeend", row);
    });
}

function updateProductCount(count) {
    productCount.textContent = `(${count})`;
}

function initializeTable() {
    const sortedData = [...productData].sort((a, b) => a.name.localeCompare(b.name));
    renderTable(sortedData);
    updateProductCount(sortedData.length);
}

initializeTable();

[brandFilter, PCIFilter, GOFilter, searchBar].forEach(filter => {
    filter.addEventListener("input", applyFiltersAndSort);
});

headers.forEach((header, index) => {
    if (index === 2 || index === 3 || index === 4) {
        header.addEventListener("click", () => {
            headers.forEach(h => h.classList.remove("sorted"));
            header.classList.add("sorted");
            if (index === 2) {
                sortOrder.rating *= -1;
            } else if (index === 3) {
                sortOrder.price *= -1;
            } else if (index === 4) {
                sortOrder.availability *= -1;
            }
            updateSortArrow(header);
            applyFiltersAndSort();
        });
    }
});

function updateSortArrow(header) {
    headers.forEach(h => {
        if (h === header) {
            const index = Array.from(headers).indexOf(header);
            const order =
                (index === 2 && sortOrder.rating === 1) ||
                (index === 3 && sortOrder.price === 1) ||
                (index === 4 && sortOrder.availability === 1)
                    ? " \u25B2"
                    : " \u25BC";
            h.textContent = h.textContent.replace(/[\u25B2\u25BC]/g, "") + order;
        } else if (h.classList.contains("cursor-pointer")) {
            h.textContent = h.textContent.replace(/[\u25B2\u25BC]/g, "");
        }
    });
}

function getAvailabilityBadge(availability) {
    const availabilityMap = {
        green: { class: "availability-green", label: "Disponible" },
        red: { class: "availability-red", label: "Indisponible" },
        orange: { class: "availability-orange", label: "Peu de stock" },
        blue: { class: "availability-blue", label: "Bientôt disponible" },
        black: { class: "availability-black", label: "Fin de série" },
    };

    const { class: className, label } = availabilityMap[availability] || { class: "availability-gray", label: "Inconnu" };

    return `
        <span class="availability-badge ${className}" title="${label}">●</span>
    `;
}

function renderStars(rating) {
    const stars = [];
    for (let i = 1; i <= 5; i++) {
        if (i <= rating) {
            stars.push('<span class="star filled">&#9733;</span>');
        } else if (i - 0.5 === rating) {
            stars.push('<span class="star half-filled">&#9733;</span>');
        } else {
            stars.push('<span class="star">&#9733;</span>');
        }
    }
    return stars.join("");
}

document.addEventListener("click", (e) => {
    if (e.target.classList.contains("star")) {
        const starRating = e.target.closest(".star-rating");
        const ratingValue = parseFloat(e.target.getAttribute("data-value"));
        starRating.setAttribute("data-rating", ratingValue);

        const stars = starRating.querySelectorAll(".star");
        stars.forEach((star, index) => {
            if (index + 1 <= ratingValue) {
                star.classList.add("filled");
                star.classList.remove("half-filled");
            } else if (index + 0.5 === ratingValue) {
                star.classList.add("half-filled");
                star.classList.remove("filled");
            } else {
                star.classList.remove("filled", "half-filled");
            }
        });
    }
});

tableBody.addEventListener("mouseover", (e) => {
    const row = e.target.closest("tr");
    if (row) {
        const productName = row.querySelector("td:first-child").textContent.trim();
        const product = productData.find(p => p.name === productName);

        if (product) {
            productImage.src = product.image;
            productImage.alt = product.name;
            productTitle.textContent = product.name;
            productDescription.textContent = product.description;
        }
    }
});

validateButton.addEventListener("click", () => {
    const selectedProducts = [];
    const checkboxes = document.querySelectorAll("tbody input[type='checkbox']:checked");
  
    checkboxes.forEach(checkbox => {
        const row = checkbox.closest("tr");
        const productName = row.querySelector("td:first-child").textContent.trim();
        const productPrice = row.querySelector(".price").textContent.trim();
        const productImage = productData.find(p => p.name === productName)?.image || "";
  
        selectedProducts.push({ 
            name: productName, 
            price: productPrice, 
            image: productImage 
        });
    });
  
    if (selectedProducts.length > 0) {
  
        let existingProducts = JSON.parse(localStorage.getItem("selectedProducts")) || [];
  
        existingProducts = existingProducts.concat(selectedProducts);
  
        localStorage.setItem("selectedProducts", JSON.stringify(existingProducts));
  
  
        console.log("Produits ajoutés au panier :", existingProducts);
  
        window.location.href = "/Website Beta/Page du panier/Panier.html";
    } else {
        alert("Veuillez sélectionner au moins une alimentation avant de valider.");
    }
  });